### PR TITLE
PARTIDEA-61 : adding new column "is_from_bo" in "proposals" table

### PR DESCRIPTION
**Pull request by vosaocms**

### CODE REVIEW

**Comment by seboo** [comment]
Please also add an "update" sql script !

**Comment by vosaocms** [comment]
Seb, 
Please take into account that there's no plugin db structure. This update is done in dump.sql used by docker.

**Comment by vosaocms** [comment]
moreover it is still the same snapshot version. Are you sure you want also an update ?

**Comment by vosaocms** [comment]
Not sure it was really necessary but I added the "update" script

**Pull request merged**
